/* Writes data/chladni-modes.js: the vibration modes of a free square plate for the Chladni page,
 * solved by Ritz's method (simulations/plate.js), so the Pi doesn't have to (a second or two
 * of its CPU for each). Run: node tools/chladni-modes.js
 *
 * Each figure is a mode { px, py, lambda, A } or, for a pair of modes of equal frequency (one
 * the other turned through 90°), one of their two combinations w(x, y) ± w(y, x), which are
 * modes too and have the square's diagonal symmetry: the figures Chladni drew.
 */
const fs = require("node:fs");
const path = require("node:path");
const Plate = require("../simulations/plate.js");

const M = 12;          // beam modes each way per parity: λ converged to ~0.05% up to 600 (vs M = 15)
const NU = 0.3;        // Poisson's ratio, steel's
const MAX_LAMBDA = 470;

const modes = Plate.solve(M, NU).filter((m) => m.lambda <= MAX_LAMBDA);
const figures = [];
// 5 significant figures, and nothing below 10⁻⁵ of the largest coefficient: plenty for a drawing
const rounder = (A) => {
	const big = Math.max(...A.flat().map(Math.abs));
	return (v) => (Math.abs(v) < 1e-5 * big ? 0 : Number(v.toPrecision(5)));
};
for (const m of modes) {
	const round = rounder(m.A), A = m.A.map((row) => row.map(round));
	if (m.px === m.py) figures.push({ px: m.px, py: m.py, lambda: Number(m.lambda.toFixed(4)), A });
	// of a pair, keep the one even in x (its twin, odd in x, is it turned through 90°): it makes
	// two figures, swaps +1 and −1
	else if (m.px === 0) figures.push({ px: 0, py: 1, lambda: Number(m.lambda.toFixed(4)), swaps: [1, -1], A });
}

const out = `/* The modes of a square plate with free edges (Poisson's ratio ${NU}), for the Chladni page:
 * generated by tools/chladni-modes.js (Ritz's method, ${M} beam modes each way per parity).
 *   px, py   parity in x and y (0 even, 1 odd)
 *   lambda   ω a² √(ρh/D), a the side
 *   A        w(x, y) = Σ A[m][n] X_m(x) X_n(y), X the free–free beam's modes (see plate.js)
 *   swaps    [1, −1]: a pair of modes, this one and itself turned through 90°, whose sum and
 *            difference make one figure each
 * Do not edit by hand.
 */
(function (root) {
	const MODES = ${JSON.stringify(figures)};
	root.ChaosChladniModes = MODES;
	if (typeof module !== "undefined") module.exports = MODES;
})(typeof window !== "undefined" ? window : globalThis);
`;
fs.writeFileSync(path.join(__dirname, "..", "data", "chladni-modes.js"), out);
const count = figures.reduce((n, f) => n + (f.swaps ? 2 : 1), 0);
console.log(`${count} figures from ${modes.length} modes up to λ = ${MAX_LAMBDA}, ${(out.length / 1024).toFixed(0)} KB`);
